version: '3'

services:
  db:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - ${MYSQL_PORT}:3306
    tty: true
    restart: always
    cap_add:
      - SYS_NICE

  schemaspy-build:
    container_name: schemaspy_build
    image: schemaspy/schemaspy:latest
    volumes:
      - ./schemaspy/output:/output
      - ./schemaspy/drivers:/drivers
    command: >
      java -jar /drivers/mysql-connector-java-8.0.19.jar
       -t mysql
       -dp /drivers
       -host db
       -port ${MYSQL_PORT}
       -db ${MYSQL_DATABASE}
       -u ${MYSQL_USER}
       -p ${MYSQL_PASSWORD}
       -s ${MYSQL_DATABASE}
       -connprops allowPublicKeyRetrieval\\=false useSSL\\=false
    depends_on:
      - db

  schemaspy-ui:
    container_name: schemaspy_ui
    image: nginx:stable
    ports:
      - ${SCHEMASPY_PORT}:80
    depends_on:
      - schemaspy-build
    volumes:
      - ./schemaspy/output:/var/www/html
      - ./nginx/schemaspy.conf.d:/etc/nginx/conf.d
    tty: true
    restart: always
